# Site settings
title: KEEP IT SKETCH MTB SKILLS & LESSONS
email: your-email@domain.com
url: https://keepitsketch.github.io
description: "Your Professional Mountain Bike Coach"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/angeloam_duff/
  - title: facebook
    url: https://www.facebook.com/KeepitsketchMTB

# Build settings
markdown: kramdown
permalink: pretty
